apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dave-getout
subjects:
- kind: ServiceAccount
  name: dave
  namespace: default
roleRef:
  kind: ClusterRole
  name: getout
  apiGroup: rbac.authorization.k8s.io
